server:
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

alertmanager:
  enabled: true
  service:
    type: ClusterIP

scrape_configs:
  - job_name: 'azure_resource_excel'
    static_configs:
      - targets: ['localhost:8000']  # ou 'localhost:8000'
