server:
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

alertmanager:
  enabled: true
  service:
    type: ClusterIP
